server:
  port: 18090

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.21.51:3306/guli-cart?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 192.168.248.134
  task:
    execution:
      thread-name-prefix: cart-task-
      pool:
        core-size: 8
        max-size: 500
        keep-alive: 60s
        queue-capacity: 1000
        allow-core-thread-timeout: true
      shutdown:
        await-termination: true
        await-termination-period: 100

  rabbitmq:
    host: 192.168.248.134
    virtual-host: /www
    username: www
    password: 123456
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        prefetch: 1

feign:
  sentinel:
    enabled: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
auth:
  jwt:
    pubKeyPath: D:\\project\\rsa\\rsa.pub;
    cookieName: GMALL_TOKEN
    userKeyName: user_key